name: Build Flet APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Python Tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK with Flet
        run: flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: X-Video-Downloader-APK
          path: build/apk/**/*.apk
