name: Build Slim APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Webview APK
        uses: itaimaz/webview-to-apk@master
        with:
          url: 'http://43.119.35.237:8866'
          name: 'X-HUB'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: X-HUB-Slim-APK
          path: ./*.apk
